@echo off
echo Starting Link Forensics Backend...
cd server
if not exist "venv" (
    echo Creating Python virtual environment...
    python -m venv venv
)
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing requirements...
pip install -r requirements.txt
echo Starting Flask App...
python app.py
pause
